// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxfmyfxflxrklihzcoem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4Zm15ZnhmbHhya2xpaHpjb2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTE0MTAsImV4cCI6MjA1OTEyNzQxMH0.r_Vl_ov7C4Ax0qWj7DTI-6JHIdhvkzg1rb2jqfgoR_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);